copy E:\www\apps\perso\app\static\js\admin.js .
copy E:\www\apps\perso\app\static\js\bankperso.default.js .
copy E:\www\apps\perso\app\static\js\bankperso.js .
copy E:\www\apps\perso\app\static\js\bankperso.manager.js .
copy E:\www\apps\perso\app\static\js\cards.js .
copy E:\www\apps\perso\app\static\js\common.js .
copy E:\www\apps\perso\app\static\js\configurator.js .
copy E:\www\apps\perso\app\static\js\controls.js .
copy E:\www\apps\perso\app\static\js\core.js .
copy E:\www\apps\perso\app\static\js\db.controller.js .
copy E:\www\apps\perso\app\static\js\login.js .
copy E:\www\apps\perso\app\static\js\log.default.js .
copy E:\www\apps\perso\app\static\js\orderstate.js .
copy E:\www\apps\perso\app\static\js\preload.js .
copy E:\www\apps\perso\app\static\js\reports.js .

I:\Python27\python.exe fminmaker.py admin
I:\Python27\python.exe fminmaker.py bankperso.default
I:\Python27\python.exe fminmaker.py bankperso
I:\Python27\python.exe fminmaker.py bankperso.manager
I:\Python27\python.exe fminmaker.py cards
I:\Python27\python.exe fminmaker.py common
I:\Python27\python.exe fminmaker.py configurator
I:\Python27\python.exe fminmaker.py controls
I:\Python27\python.exe fminmaker.py core
I:\Python27\python.exe fminmaker.py db.controller
I:\Python27\python.exe fminmaker.py login
I:\Python27\python.exe fminmaker.py log.default
I:\Python27\python.exe fminmaker.py orderstate
I:\Python27\python.exe fminmaker.py preload
I:\Python27\python.exe fminmaker.py reports

copy *.min.js E:\www\apps\perso\app\static\js